module.exports = {
    GOT_CARDS : "GOT_CARDS",
    BID_RESPONSE: "BID_RESPONSE",
    LOGIN: "LOGIN",
    CREATE_ROOM: "CREATE_ROOM",
    JOIN_ROOM: "JOIN_ROOM",
    ROOMS_REQUEST: "ROOMS_REQUEST",
    LEAVE_ROOM: "LEAVE_ROOM",
    START_GAME: "START_GAME",
    CARD_RESPONSE: "CARD_RESPONSE",
    DISCONNECT: "disconnect",

    GOT_PLAYERS: "GOT_PLAYERS",
    GOT_BID_STATUS: "GOT_BID_STATUS",
    GOT_TABLE_STATUS: "GOT_TABLE_STATUS",
    GOT_WINNER:"GOT_WINNER",
    GOT_SCORE: "GOT_SCORE",

}