module.exports = {
    ERROR : "ERROR",
    CONNECTED: "CONNECTED",
    TOKEN: "TOKEN",
    LOBBY: "LOBBY",
    CARD_REQUEST: "CARD_REQUEST",
    KICK_ALL: "KICK_ALL",
    GET_CARDS: "GET_CARDS",
    BID_REQUEST: "BID_REQUEST",
    ROOMS_RESPONSE: "ROOMS_RESPONSE",
    PLAYERS_REQUEST: "PLAYER_REQUEST",
    
    BID_STATUS: "BID_STATUS",
    TABLE_STATUS: "TABLE_STATUS",
    SCORE_STATUS: "SCORE_STATUS",
    WINNER: "WINNER",
    END_GAME: "END_GAME",
}